### PR TITLE
feat: add region and service to AWS destination auth

### PR DESCRIPTION
**Pull request by leggetter**
```
Terraform will perform the following actions:

  # hookdeck_destination.aws_destination will be created
  + resource "hookdeck_destination" "aws_destination" {
      + auth_method              = {
          + aws_signature = {
              + access_key_id     = (sensitive value)
              + region            = "us-west-2"
              + secret_access_key = (sensitive value)
              + service           = "lambda"
            }
        }
      + created_at               = (known after apply)
      + disabled_at              = (known after apply)
      + id                       = (known after apply)
      + name                     = "aws_destination"
      + path_forwarding_disabled = (known after apply)
      + team_id                  = (known after apply)
      + updated_at               = (known after apply)
      + url                      = "https://mock.hookdeck.com"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### CODE REVIEW

**Review by alexluong — APPROVED** [review]
LGTM!

**Comment by leggetter** [comment]
> LGTM!

But https://github.com/hookdeck/terraform-provider-hookdeck/pull/116#issue-2603612452 should have `service` and `region`

Here's the file: https://github.com/hookdeck/terraform-provider-hookdeck/pull/116/files#diff-c0daa08d1f19fc83e2ca82d030dd869b884b9355373b3e2610d2fda8dbea613fR69-R81

**Comment by alexluong** [comment]
@leggetter ah I missed that, let me take a look.

**Comment by alexluong** [comment]
@leggetter have you run `go install .` to build & use the new code? It seems to work correctly for me.

**Comment by leggetter** [comment]
> @leggetter have you run `go install .` to build & use the new code? It seems to work correctly for me.

@alexluong - ah, I forgot the install step. Thanks 👍

**Pull request merged**
