### PR TITLE
build: Separate TF docs & source verification codegen generate commands

### PR DESCRIPTION
**Pull request by alexluong**
This PR allows us to choose what we want to generate

```sh
# source verification generation
$ make generate-codegen

# Terraform docs generation
$ make generate-tfdocs
```

Other CI configuration:

- [ ] 1. Whenever there's a new release in [hookdeck/hookdeck-go-sdk](https://github.com/hookdeck/hookdeck-go-sdk), we should open a PR in this repo with the codegen updates.
- [ ] 2. Automatic TF docs generation on PR merge

## Automatic TF docs generation on PR merge

**Implementation**

We can consider using something like [this action](https://github.com/stefanzweifel/git-auto-commit-action) after running `make generate-tfdocs` on push to `main`.

**Consideration**

Currently in `test` GH action, we check if there's a diff when running tfdocs. Should we disable that test then?

The main thing I appreciate about that workflow is that it forces me (dev) to be mindful of changes that affect the API surface of the provider. Sometimes I thought a change was internal but it ended up affecting some schema and I'm reminded to add some documentation to explain the schema change.

### CODE REVIEW

**Comment by leggetter** [comment]
@alexluong :

> Currently in test GH action, we check if there's a diff when running tfdocs. Should we disable that test then?

Yes, we should remove that.

What the dev workflow should be now is that you will look at the PR to see if there are any unexpected changes in the generated docs and code. This obviously doesn't stop you doing the check locally, too.

**Comment by alexluong** [comment]
@leggetter oh so when does the docgen GH Action run? On every push?

Is it a bit awkward that you can push something and local and remote automatically drift, so if you commit to local and may cause a conflict later?

**Comment by leggetter** [comment]
> @leggetter oh so when does the docgen GH Action run? On every push?
> 
> Is it a bit awkward that you can push something and local and remote automatically drift, so if you commit to local and may cause a conflict later?

@alexluong - how about a commit [hook](https://git-scm.com/book/ms/v2/Customizing-Git-Git-Hooks) instead?

**Comment by alexluong** [comment]
@leggetter yeah a commit hook may make more sense. So we run docgen every precommit?

**Comment by leggetter** [comment]
> @leggetter yeah a commit hook may make more sense. So we run docgen every precommit?

@alexluong yeah 👍

**Comment by alexluong** [comment]
@leggetter yes, we should! Is there anything else in this PR before we can merge it?

**Pull request merged**
