### PR TITLE
feat: Add support for Bondsmith and Fiserv source verification

### LINKED ISSUE #38: Update to new Go SDK v0.3.8 and add new source and verification support
See https://github.com/hookdeck/hookdeck-go-sdk/releases/tag/v0.0.38

### PR DESCRIPTION
**Pull request by alexluong**
resolves #38

### CODE REVIEW

**Review by alexbouchardd — APPROVED** [review]

**Comment by leggetter** [comment]
@alexluong - could we also add https://github.com/hookdeck/terraform-provider-hookdeck/issues/49 to this PR? The required functionality should be in the latest SDK.

**Comment by alexluong** [comment]
@leggetter certainly! I did mention it to you as well. There are a few more than just AWS Signature that we haven't supported tho. Should we add them as well?

In either case, any reason why we can't merge this and follow up on that later? They're separate enough that I don't see a strong reason why they should be in the same PR.

**Comment by leggetter** [comment]
> @leggetter certainly! I did mention it to you as well. There are a few more than just AWS Signature that we haven't supported tho. Should we add them as well?
> 
> In either case, any reason why we can't merge this and follow up on that later? They're separate enough that I don't see a strong reason why they should be in the same PR.

@alexluong, the AWS Signature one is a priority, so it'd be great to see that one ASAP 🙏 But I'll merge this one as addressing verifications only.

**Comment by alexluong** [comment]
@leggetter ah I see, noted on the priority of the AWS Signature and will work on that soon!

**Comment by alexbouchardd** [comment]
@alexluong Could we also add a json bypass for the destination auth so that there's a workaround when more are added?

**Pull request merged**
